function(print_options)
    cmake_parse_arguments(PARSE_ARGV 0 IN "" "" "OPTIONS")
    foreach (OPT ${IN_OPTIONS})
        if(VTFLIB_${OPT})
            message(STATUS "[X] VTFLIB_${OPT}")
        else()
            message(STATUS "[ ] VTFLIB_${OPT}")
        endif()
    endforeach()
endfunction()
